// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR2Z7cbNDXFdhEqyyR7JaHhXhrmLJUyfY',
    appId: '1:616452036876:web:4deec1c5916424f3b75129',
    messagingSenderId: '616452036876',
    projectId: 'gemini-4f77d',
    authDomain: 'gemini-4f77d.firebaseapp.com',
    storageBucket: 'gemini-4f77d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRZhUUO9A_494VozFt6B_Kq2GLRQLgMFA',
    appId: '1:616452036876:android:e2e9a71796388322b75129',
    messagingSenderId: '616452036876',
    projectId: 'gemini-4f77d',
    storageBucket: 'gemini-4f77d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGmNuDa1Kcxv-RjuL4QK--XHuKQ0Ykovs',
    appId: '1:616452036876:ios:d3e85d31ed2954d4b75129',
    messagingSenderId: '616452036876',
    projectId: 'gemini-4f77d',
    storageBucket: 'gemini-4f77d.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGmNuDa1Kcxv-RjuL4QK--XHuKQ0Ykovs',
    appId: '1:616452036876:ios:d3e85d31ed2954d4b75129',
    messagingSenderId: '616452036876',
    projectId: 'gemini-4f77d',
    storageBucket: 'gemini-4f77d.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR2Z7cbNDXFdhEqyyR7JaHhXhrmLJUyfY',
    appId: '1:616452036876:web:514bd307477c5defb75129',
    messagingSenderId: '616452036876',
    projectId: 'gemini-4f77d',
    authDomain: 'gemini-4f77d.firebaseapp.com',
    storageBucket: 'gemini-4f77d.firebasestorage.app',
  );
}
